# Generated by Django 4.1.4 on 2022-12-30 04:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=25)),
                ('prenClient', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVend', models.CharField(max_length=25)),
                ('prenVend', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('adresse', models.CharField(max_length=100)),
                ('refDepot', models.CharField(max_length=100)),
                ('qteDepot', models.IntegerField(default=0)),
                ('montantPerçu', models.IntegerField(default=0)),
                ('Date_heure_depot', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_entreprise.client')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudoAdmin', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending', max_length=50)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_entreprise.vendeur')),
            ],
        ),
    ]
